### ISSUE TITLE
multi-checker.yml inputs are ignored

### ISSUE THREAD

**Issue by mwasilew** [qualcomm-linux/qli-actions#6]
Attempts to disable checks in multi-checker fail. Call with all checks disabled will result in all being used:

```
jobs:
  checker:
    uses: qualcomm-linux/qli-actions/.github/workflows/multi-checker.yml@main
    with:
        repolinter: false # default: true
        semgrep: false # default: true
        copyright-license-detector: false # default: true
        pr-check-emails: false # default: true

```
This results in the following run: https://github.com/qualcomm-linux/qcom-linux-testkit/actions/runs/15341048199?pr=57

This happens most likely because boolean inputs are not supported in github actions.
